version: '3.1'

networks:
  kitchen_network:

services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: demo
    networks:
      - kitchen_network
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: kitchen
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: demo
      MYSQL_HOST: demo
    ports:
      - "3306:3306"
    networks:
      - kitchen_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
